<a href="https://colab.research.google.com/github/salianbharat/Basic-/blob/main/Penguins.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from google.colab import files
upload_file = files.upload ()

Saving penguins.csv to penguins.csv


In [4]:
#Import the required libraries
from sklearn.cluster import DBSCAN
from sklearn.preprocessing import StandardScaler
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [ ]:
df = pd.read_csv("penguins.csv")
df.head()

In [7]:
df.describe()

culmen_length_mm  culmen_depth_mm  flipper_length_mm  body_mass_g
count        342.000000       342.000000         342.000000   342.000000
mean          43.921930        17.151170         214.014620  4201.754386
std            5.459584         1.974793         260.558057   801.954536
min           32.100000        13.100000        -132.000000  2700.000000
25%           39.225000        15.600000         190.000000  3550.000000
50%           44.450000        17.300000         197.000000  4050.000000
75%           48.500000        18.700000         213.750000  4750.000000
max           59.600000        21.500000        5000.000000  6300.000000

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   culmen_length_mm   342 non-null    float64
 1   culmen_depth_mm    342 non-null    float64
 2   flipper_length_mm  342 non-null    float64
 3   body_mass_g        342 non-null    float64
 4   sex                335 non-null    object 
dtypes: float64(4), object(1)
memory usage: 13.6+ KB


In [9]:
df.drop('sex',axis = 1, inplace = True )

In [13]:
array = df.values
array

array([[  39.1,   18.7,  181. , 3750. ],
       [  39.5,   17.4,  186. , 3800. ],
       [  40.3,   18. ,  195. , 3250. ],
       ...,
       [  50.4,   15.7,  222. , 5750. ],
       [  45.2,   14.8,  212. , 5200. ],
       [  49.9,   16.1,  213. , 5400. ]])

In [17]:
df = pd.DataFrame(array)

In [ ]:
df = df.fillna(0)
df

In [23]:
array1 = df.values

In [24]:
stdscaler = StandardScaler().fit(array1)
x = stdscaler.transform(array1)

In [25]:
x

array([[-7.15821262e-01,  6.98756086e-01, -1.22226944e-01,
        -4.96900475e-01],
       [-6.53120259e-01,  1.47735593e-01, -1.02990935e-01,
        -4.38759739e-01],
       [-5.27718253e-01,  4.02052743e-01, -6.83661183e-02,
        -1.07830783e+00],
       ...,
       [ 1.05548207e+00, -5.72829667e-01,  3.55083307e-02,
         1.82872896e+00],
       [ 2.40369034e-01, -9.54305393e-01, -2.96368744e-03,
         1.18918086e+00],
       [ 9.77105820e-01, -4.03284900e-01,  8.83514370e-04,
         1.42174381e+00]])

In [35]:
dbscan = DBSCAN (eps = 5.8,min_samples = 4)
dbscan.fit(x)

DBSCAN(eps=5.8, min_samples=4)

In [36]:
dbscan.labels_

array([ 0,  0,  0, -1,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0

In [37]:
cl = pd.DataFrame(dbscan.labels_,columns =['cluster'])
cl

cluster
0          0
1          0
2          0
3         -1
4          0
..       ...
339       -1
340        0
341        0
342        0
343        0

[344 rows x 1 columns]

In [38]:
clustered = pd.concat([df,cl], axis =1)


In [43]:
clustered.head(5)

0     1      2       3  cluster
0  39.1  18.7  181.0  3750.0        0
1  39.5  17.4  186.0  3800.0        0
2  40.3  18.0  195.0  3250.0        0
3   0.0   0.0    0.0     0.0       -1
4  36.7  19.3  193.0  3450.0        0

In [44]:
clustered[clustered['cluster']==-1]

0     1       2       3  cluster
3     0.0   0.0     0.0     0.0       -1
9    42.0  20.2  5000.0  4250.0       -1
339   0.0   0.0     0.0     0.0       -1

In [45]:
from sklearn.metrics import silhouette_score
labels = dbscan.labels_

print("Silhouette Coeffient: %0.3f"
% silhouette_score(x, labels))

Silhouette Coeffient: 0.850
